version: '3.9'
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - '8000:8000'
    container_name: web-app
    restart: always
    depends_on:
      - db
    networks:
      - postgres
    env_file:
      - ./.env

  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    container_name: pg-data
    restart: always
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    command: "postgres -c listen_addresses='*'"
    networks:
      - postgres

volumes:
  pgdata:

networks:
  postgres:
    driver: bridge
